# In-Class Challenge Assignment: Experimenting with the Perceptron
# Day 18 Extension
# CMSE 202

## Now that you have a working Perceptron Classifier... let's experiment with it a bit!

When building and testing your Perceptron Classifier you used a simplified version of the iris dataset that has been reduced to just two features and two class labels. 

### Will your Perceptron classifier work on a more complex dataset?

Another widely used dataset for experimenting with binary classification is the [sonar dataset](https://archive.ics.uci.edu/ml/datasets/Connectionist+Bench+(Sonar,+Mines+vs.+Rocks)).

A version of this dataset can be found here:

`https://raw.githubusercontent.com/msu-cmse-courses/cmse202-F22-data/main/data/sonar.csv`

Make sure you take a moment to read the [UC Irvine Machine Learning Repository page](https://archive.ics.uci.edu/ml/datasets/Connectionist+Bench+(Sonar,+Mines+vs.+Rocks)) to understand exactly what is in this dataset, but essentially is a collection of sonar measurements of rocks and "mines" (metal cynlinders).

---
### Testing your new tool and exploring others

With any time that you have left in class, see if you can accomplish the following:

1. Load up the sonar dataset and change the class labels so that they can be used with the Perceptron classifier.

2. Use the Perceptron classifier you built from scratch to see how well you can do at distinguishing rocks from mines. You may need to make some modifications to your code if you didn't build it to be flexible enough to accept an arbitary number of data deatures. Experiment with the learning rate and number of iterations to see how high of an accuracy you can get with your classifier.

3. If you get your Perceptron classifier working, can you figure out how to use the Perceptron Classifier that is available in [scikit-learn](https://scikit-learn.org/stable/index.html)? You may need to do a bit of Google searching and exploration of the documentation to figure this out. How well does the scikit-learn version do compared to the one you built?

4. If you're feeling really ambitious, can you build a Perceptron classifier with [Tensorflow](https://www.tensorflow.org/)? Remember, the Perceptron is basically just a single-neuron single-layer neural network.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!curl -O https://raw.githubusercontent.com/msu-cmse-courses/cmse202-F22-data/main/data/sonar.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 87486  100 87486    0     0  3417k      0 --:--:-- --:--:-- --:--:-- 3417k

In [3]:
sonar = pd.read_csv('sonar.csv')
sonar.tail()

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60,Class
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,Mine
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,Mine
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,Mine
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,Mine
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,Mine

In [4]:
for i in range(len(sonar)):
    if sonar['Class'][i] == 'Rock':
        sonar['Class'][i] = -1
    else:
        sonar['Class'][i] = 1
sonar.head()

<ipython-input-4-d03fc793c747>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sonar['Class'][i] = -1
<ipython-input-4-d03fc793c747>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sonar['Class'][i] = 1

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,-1
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,-1
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,-1
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,-1
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,-1

In [147]:
class Perceptron():

    def __init__ (self, n, labeled_data, iters, learning_rate):        
        # attributes now are: number of features (n), data, weights, iterations, learning rate
        self.data = labeled_data
        self.n=n
        self.weights = np.ones(self.n+1)
        self.iterations = iters
        self.learning_rate = learning_rate
        
    def predict(self, feature_set):
        dot_product = np.dot(feature_set, self.weights) + (self.weights[0])
        if dot_product[0] > 0:
            return 1
        else:
            return -1
        
    def fit(self):
        for i in range(self.iterations):
            for row in range(len(self.data)):
                for k in range(self.n-1):
                    self.weights[k+1] = self.weights[k+1] + (self.learning_rate * (self.data[row][0][2] - self.predict([self.data[row][0]])) * self.data[row][0][k])
                    self.weights[0] = self.weights[0] + (self.learning_rate * (self.data[row][2] - self.predict([self.data[row][0]])))
        return self.weights
        # for all iterations
        #    for each row in the data
        #        find the update value, changes the weights (including bias weight)

    def errors(self):
#         how many rows of the data don't match the provided label?
        errors=0
        for i in range(len(self.data)):
            if self.predict([self.data[i][0],self.data[i][1]]) != self.data[i][2]:
                errors+=1
            else:
                pass
        return errors

In [204]:
f = open("sonar.csv")
header = next(f) # dump the header line
data = []
for line in f:
    fields = line.split(",")
    # need to strip label because, as the last element, it has a \n
    label = (1.0 if fields[60].strip() == "Mine" else -1.0)
    # the fields are strings until we conver them
    for i in range(60):
        data.append(float(fields[i]))
    data.append(label)
f.close()
p = Perceptron(60, data, 10, 0.01)
p.fit()
p.errors()
# (data)

TypeError: 'float' object is not subscriptable

In [205]:
data

[0.02,
 0.0371,
 0.0428,
 0.0207,
 0.0954,
 0.0986,
 0.1539,
 0.1601,
 0.3109,
 0.2111,
 0.1609,
 0.1582,
 0.2238,
 0.0645,
 0.066,
 0.2273,
 0.31,
 0.2999,
 0.5078,
 0.4797,
 0.5783,
 0.5071,
 0.4328,
 0.555,
 0.6711,
 0.6415,
 0.7104,
 0.808,
 0.6791,
 0.3857,
 0.1307,
 0.2604,
 0.5121,
 0.7547,
 0.8537,
 0.8507,
 0.6692,
 0.6097,
 0.4943,
 0.2744,
 0.051,
 0.2834,
 0.2825,
 0.4256,
 0.2641,
 0.1386,
 0.1051,
 0.1343,
 0.0383,
 0.0324,
 0.0232,
 0.0027,
 0.0065,
 0.0159,
 0.0072,
 0.0167,
 0.018,
 0.0084,
 0.009,
 0.0032,
 -1.0,
 0.0453,
 0.0523,
 0.0843,
 0.0689,
 0.1183,
 0.2583,
 0.2156,
 0.3481,
 0.3337,
 0.2872,
 0.4918,
 0.6552,
 0.6919,
 0.7797,
 0.7464,
 0.9444,
 1.0,
 0.8874,
 0.8024,
 0.7818,
 0.5212,
 0.4052,
 0.3957,
 0.3914,
 0.325,
 0.32,
 0.3271,
 0.2767,
 0.4423,
 0.2028,
 0.3788,
 0.2947,
 0.1984,
 0.2341,
 0.1306,
 0.4182,
 0.3835,
 0.1057,
 0.184,
 0.197,
 0.1674,
 0.0583,
 0.1401,
 0.1628,
 0.0621,
 0.0203,
 0.053,
 0.0742,
 0.0409,
 0.0061,
 0.0125,
 0.0084,
 0.0089,
 0.0048,
 0.0094,
 0.0191,
 0.014,
 0.0049,
 0.0052,
 0.0044,
 -1.0,
 0.0262,
 0.0582,
 0.1099,
 0.1083,
 0.0974,
 0.228,
 0.2431,
 0.3771,
 0.5598,
 0.6194,
 0.6333,
 0.706,
 0.5544,
 0.532,
 0.6479,
 0.6931,
 0.6759,
 0.7551,
 0.8929,
 0.8619,
 0.7974,
 0.6737,
 0.4293,
 0.3648,
 0.5331,
 0.2413,
 0.507,
 0.8533,
 0.6036,
 0.8514,
 0.8512,
 0.5045,
 0.1862,
 0.2709,
 0.4232,
 0.3043,
 0.6116,
 0.6756,
 0.5375,
 0.4719,
 0.4647,
 0.2587,
 0.2129,
 0.2222,
 0.2111,
 0.0176,
 0.1348,
 0.0744,
 0.013,
 0.0106,
 0.0033,
 0.0232,
 0.0166,
 0.0095,
 0.018,
 0.0244,
 0.0316,
 0.0164,
 0.0095,
 0.0078,
 -1.0,
 0.01,
 0.0171,
 0.0623,
 0.0205,
 0.0205,
 0.0368,
 0.1098,
 0.1276,
 0.0598,
 0.1264,
 0.0881,
 0.1992,
 0.0184,
 0.2261,
 0.1729,
 0.2131,
 0.0693,
 0.2281,
 0.406,
 0.3973,
 0.2741,
 0.369,
 0.5556,
 0.4846,
 0.314,
 0.5334,
 0.5256,
 0.252,
 0.209,
 0.3559,
 0.626,
 0.734,
 0.612,
 0.3497,
 0.3953,
 0.3012,
 0.5408,
 0.8814,
 0.9857,
 0.9167,
 0.6121,
 0.5006,
 0.321,
 0.3202,
 0.4295,
 0.3654,
 0.2655,
 0.1576,
 0.0681,
 0.0294,
 0.0241,
 0.0121,
 0.0036,
 0.015,
 0.0085,
 0.0073,
 0.005,
 0.0044,
 0.004,
 0.0117,
 -1.0,
 0.0762,
 0.0666,
 0.0481,
 0.0394,
 0.059,
 0.0649,
 0.1209,
 0.2467,
 0.3564,
 0.4459,
 0.4152,
 0.3952,
 0.4256,
 0.4135,
 0.4528,
 0.5326,
 0.7306,
 0.6193,
 0.2032,
 0.4636,
 0.4148,
 0.4292,
 0.573,
 0.5399,
 0.3161,
 0.2285,
 0.6995,
 1.0,
 0.7262,
 0.4724,
 0.5103,
 0.5459,
 0.2881,
 0.0981,
 0.1951,
 0.4181,
 0.4604,
 0.3217,
 0.2828,
 0.243,
 0.1979,
 0.2444,
 0.1847,
 0.0841,
 0.0692,
 0.0528,
 0.0357,
 0.0085,
 0.023,
 0.0046,
 0.0156,
 0.0031,
 0.0054,
 0.0105,
 0.011,
 0.0015,
 0.0072,
 0.0048,
 0.0107,
 0.0094,
 -1.0,
 0.0286,
 0.0453,
 0.0277,
 0.0174,
 0.0384,
 0.099,
 0.1201,
 0.1833,
 0.2105,
 0.3039,
 0.2988,
 0.425,
 0.6343,
 0.8198,
 1.0,
 0.9988,
 0.9508,
 0.9025,
 0.7234,
 0.5122,
 0.2074,
 0.3985,
 0.589,
 0.2872,
 0.2043,
 0.5782,
 0.5389,
 0.375,
 0.3411,
 0.5067,
 0.558,
 0.4778,
 0.3299,
 0.2198,
 0.1407,
 0.2856,
 0.3807,
 0.4158,
 0.4054,
 0.3296,
 0.2707,
 0.265,
 0.0723,
 0.1238,
 0.1192,
 0.1089,
 0.0623,
 0.0494,
 0.0264,
 0.0081,
 0.0104,
 0.0045,
 0.0014,
 0.0038,
 0.0013,
 0.0089,
 0.0057,
 0.0027,
 0.0051,
 0.0062,
 -1.0,
 0.0317,
 0.0956,
 0.1321,
 0.1408,
 0.1674,
 0.171,
 0.0731,
 0.1401,
 0.2083,
 0.3513,
 0.1786,
 0.0658,
 0.0513,
 0.3752,
 0.5419,
 0.544,
 0.515,
 0.4262,
 0.2024,
 0.4233,
 0.7723,
 0.9735,
 0.939,
 0.5559,
 0.5268,
 0.6826,
 0.5713,
 0.5429,
 0.2177,
 0.2149,
 0.5811,
 0.6323,
 0.2965,
 0.1873,
 0.2969,
 0.5163,
 0.6153,
 0.4283,
 0.5479,
 0.6133,
 0.5017,
 0.2377,
 0.1957,
 0.1749,
 0.1304,
 0.0597,
 0.1124,
 0.1047,
 0.0507,
 0.0159,
 0.0195,
 0.0201,
 0.0248,
 0.0131,
 0.007,
 0.0138,
 0.0092,
 0.0143,
 0.0036,
 0.0103,
 -1.0,
 0.0519,
 0.0548,
 0.0842,
 0.0319,
 0.1158,
 0.0922,
 0.1027,
 0.0613,
 0.1465,
 0.2838,
 0.2802,
 0.3086,
 0.2657,
 0.3801,
 0.5626,
 0.4376,
 0.2617,
 0.1199,
 0.6676,
 0.9402,
 0.7832,
 0.5352,
 0.6809,
 0.9174,
 0.7613,
 0.822,
 0.8872,
 0.6091,
 0.2967,
 0.1103,
 0.1318,
 0.0624,
 0.099,
 0.4006,
 0.3666,
 0.105,
 0.1915,
 0.393,
 0.4288,
 0.2546,
 0.1151,
 0.2196,
 0.1879,
 0.1437,
 0.2146,
 0.236,
 0.1125,
 0.0254,
 0.0285,
 0.0178,
 0.0052,
 0.0081,
 0.012,
 0.0045,
 0.0121,
 0.0097,
 0.0085,
 0.0047,
 0.0048,
 0.0053,
 -1.0,
 0.0223,
 0.0375,
 0.0484,
 0.0475,
 0.0647,
 0.0591,
 0.0753,
 0.0098,
 0.0684,
 0.1487,
 0.1156,
 0.1654,
 0.3833,
 0.3598,
 0.1713,
 0.1136,
 0.0349,
 0.3796,
 0.7401,
 0.9925,
 0.9802,
 0.889,
 0.6712,
 0.4286,
 0.3374,
 0.7366,
 0.9611,
 0.7353,
 0.4856,
 0.1594,
 0.3007,
 0.4096,
 0.317,
 0.3305,
 0.3408,
 0.2186,
 0.2463,
 0.2726,
 0.168,
 0.2792,
 0.2558,
 0.174,
 0.2121,
 0.1099,
 0.0985,
 0.1271,
 0.1459,
 0.1164,
 0.0777,
 0.0439,
 0.0061,
 0.0145,
 0.0128,
 0.0145,
 0.0058,
 0.0049,
 0.0065,
 0.0093,
 0.0059,
 0.0022,
 -1.0,
 0.0164,
 0.0173,
 0.0347,
 0.007,
 0.0187,
 0.0671,
 0.1056,
 0.0697,
 0.0962,
 0.0251,
 0.0801,
 0.1056,
 0.1266,
 0.089,
 0.0198,
 0.1133,
 0.2826,
 0.3234,
 0.3238,
 0.4333,
 0.6068,
 0.7652,
 0.9203,
 0.9719,
 0.9207,
 0.7545,
 0.8289,
 0.8907,
 0.7309,
 0.6896,
 0.5829,
 0.4935,
 0.3101,
 0.0306,
 0.0244,
 0.1108,
 0.1594,
 0.1371,
 0.0696,
 0.0452,
 0.062,
 0.1421,
 0.1597,
 0.1384,
 0.0372,
 0.0688,
 0.0867,
 0.0513,
 0.0092,
 0.0198,
 0.0118,
 0.009,
 0.0223,
 0.0179,
 0.0084,
 0.0068,
 0.0032,
 0.0035,
 0.0056,
 0.004,
 -1.0,
 0.0039,
 0.0063,
 0.0152,
 0.0336,
 0.031,
 0.0284,
 0.0396,
 0.0272,
 0.0323,
 0.0452,
 0.0492,
 0.0996,
 0.1424,
 0.1194,
 0.0628,
 0.0907,
 0.1177,
 0.1429,
 0.1223,
 0.1104,
 0.1847,
 0.3715,
 0.4382,
 0.5707,
 0.6654,
 0.7476,
 0.7654,
 0.8555,
 0.972,
 0.9221,
 0.7502,
 0.7209,
 0.7757,
 0.6055,
 0.5021,
 0.4499,
 0.3947,
 0.4281,
 0.4427,
 0.3749,
 0.1972,
 0.0511,
 0.0793,
 0.1269,
 0.1533,
 0.069,
 0.0402,
 0.0534,
 0.0228,
 0.0073,
 0.0062,
 0.0062,
 0.012,
 0.0052,
 0.0056,
 0.0093,
 0.0042,
 0.0003,
 0.0053,
 0.0036,
 -1.0,
 0.0123,
 0.0309,
 0.0169,
 0.0313,
 0.0358,
 0.0102,
 0.0182,
 0.0579,
 0.1122,
 0.0835,
 0.0548,
 0.0847,
 0.2026,
 0.2557,
 0.187,
 0.2032,
 0.1463,
 0.2849,
 0.5824,
 0.7728,
 0.7852,
 0.8515,
 0.5312,
 0.3653,
 0.5973,
 0.8275,
 1.0,
 0.8673,
 0.6301,
 0.4591,
 0.394,
 0.2576,
 0.2817,
 0.2641,
 0.2757,
 0.2698,
 0.3994,
 0.4576,
 0.394,
 0.2522,
 0.1782,
 0.1354,
 0.0516,
 0.0337,
 0.0894,
 0.0861,
 0.0872,
 0.0445,
 0.0134,
 0.0217,
 0.0188,
 0.0133,
 0.0265,
 0.0224,
 0.0074,
 0.0118,
 0.0026,
 0.0092,
 0.0009,
 0.0044,
 -1.0,
 0.0079,
 0.0086,
 0.0055,
 0.025,
 0.0344,
 0.0546,
 0.0528,
 0.0958,
 0.1009,
 0.124,
 0.1097,
 0.1215,
 0.1874,
 0.3383,
 0.3227,
 0.2723,
 0.3943,
 0.6432,
 0.7271,
 0.8673,
 0.9674,
 0.9847,
 0.948,
 0.8036,
 0.6833,
 0.5136,
 0.309,
 0.0832,
 0.4019,
 0.2344,
 0.1905,
 0.1235,
 0.1717,
 0.2351,
 0.2489,
 0.3649,
 0.3382,
 0.1589,
 0.0989,
 0.1089,
 0.1043,
 0.0839,
 0.1391,
 0.0819,
 0.0678,
 0.0663,
 0.1202,
 0.0692,
 0.0152,
 0.0266,
 0.0174,
 0.0176,
 0.0127,
 0.0088,
 0.0098,
 0.0019,
 0.0059,
 0.0058,
 0.0059,
 0.0032,
 -1.0,
 0.009,
 0.0062,
 0.0253,
 0.0489,
 0.1197,
 0.1589,
 0.1392,
 0.0987,
 0.0955,
 0.1895,
 0.1896,
 0.2547,
 0.4073,
 0.2988,
 0.2901,
 0.5326,
 0.4022,
 0.1571,
 0.3024,
 0.3907,
 0.3542,
 0.4438,
 0.6414,
 0.4601,
 0.6009,
 0.869,
 0.8345,
 0.7669,
 0.5081,
 0.462,
 0.538,
 0.5375,
 0.3844,
 0.3601,
 0.7402,
 0.7761,
 0.3858,
 0.0667,
 0.3684,
 0.6114,
 0.351,
 0.2312,
 0.2195,
 0.3051,
 0.1937,
 0.157,
 0.0479,
 0.0538,
 0.0146,
 0.0068,
 0.0187,
 0.0059,
 0.0095,
 0.0194,
 0.008,
 0.0152,
 0.0158,
 0.0053,
 0.0189,
 0.0102,
 -1.0,
 0.0124,
 0.0433,
 0.0604,
 0.0449,
 0.0597,
 0.0355,
 0.0531,
 0.0343,
 0.1052,
 0.212,
 0.164,
 0.1901,
 0.3026,
 0.2019,
 0.0592,
 0.239,
 0.3657,
 0.3809,
 0.5929,
 0.6299,
 0.5801,
 0.4574,
 0.4449,
 0.3691,
 0.6446,
 0.894,
 0.8978,
 0.498,
 0.3333,
 0.235,
 0.1553,
 0.3666,
 0.434,
 0.3082,
 0.3024,
 0.4109,
 0.5501,
 0.4129,
 0.5499,
 0.5018,
 0.3132,
 0.2802,
 0.2351,
 0.2298,
 0.1155,
 0.0724,
 0.0621,
 0.0318,
 0.045,
 0.0167,
 0.0078,
 0.0083,
 0.0057,
 0.0174,
 0.0188,
 0.0054,
 0.0114,
 0.0196,
 0.0147,
 0.0062,
 -1.0,
 0.0298,
 0.0615,
 0.065,
 0.0921,
 0.1615,
 0.2294,
 0.2176,
 0.2033,
 0.1459,
 0.0852,
 0.2476,
 0.3645,
 0.2777,
 0.2826,
 0.3237,
 0.4335,
 0.5638,
 0.4555,
 0.4348,
 0.6433,
 0.3932,
 0.1989,
 0.354,
 0.9165,
 0.9371,
 0.462,
 0.2771,
 0.6613,
 0.8028,
 0.42,
 0.5192,
 0.6962,
 0.5792,
 0.8889,
 0.7863,
 0.7133,
 0.7615,
 0.4401,
 0.3009,
 0.3163,
 0.2809,
 0.2898,
 0.0526,
 0.1867,
 0.1553,
 0.1633,
 0.1252,
 0.0748,
 0.0452,
 0.0064,
 0.0154,
 0.0031,
 0.0153,
 0.0071,
 0.0212,
 0.0076,
 0.0152,
 0.0049,
 0.02,
 0.0073,
 -1.0,
 0.0352,
 0.0116,
 0.0191,
 0.0469,
 0.0737,
 0.1185,
 0.1683,
 0.1541,
 0.1466,
 0.2912,
 0.2328,
 0.2237,
 0.247,
 0.156,
 0.3491,
 0.3308,
 0.2299,
 0.2203,
 0.2493,
 0.4128,
 0.3158,
 0.6191,
 0.5854,
 0.3395,
 ...]

In [189]:
dot_product = np.dot(data[0][0], np.ones(61)) + (np.ones(61)[0])

ValueError: data type must provide an itemsize

In [190]:
dot_product[0]

1.02

&#169; Copyright Department of Computational Mathematics, Science and Engineering; Michigan State University